apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: server-auto-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-depl
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis-auto-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-depl
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75